### ISSUE TITLE
pytorch 0.4.1 deprecated

### ISSUE THREAD

**Issue by MadisLemsalu** [AydarAkhmetzyanov/Openpose_dockerized_flask_microservice#1]
Could not find a version that satisfies the requirement torch==0.4.1.post2 (from -r /var/folders/h3/59qfw93n6k92mh9lqzvpb1480000gn/T/pipenv-36_h8mxg-requirements/pipenv-wg1__hmp-requirement.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.4.1)
No matching distribution found for torch==0.4.1.post2 (from -r /var/folders/h3/59qfw93n6k92mh9lqzvpb1480000gn/T/pipenv-36_h8mxg-requirements/pipenv-wg1__hmp-requirement.txt (line 1))

Can't be installed. Any workarounds?

**Comment by AydarAkhmetzyanov** [comment]
I think you can update the version of torch

**Comment by MadisLemsalu** [comment]
Yes in the end this worked: pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
